### ISSUE TITLE
GM doesn't work on 1.20

### ISSUE THREAD

**Issue by Budderman18** [ElgarL/GroupManager#100]
This message shows up in both Loading and Enabling

'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)' initializing Geyser-Spigot v2.1.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'
        at org.geysermc.geyser.platform.spigot.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:191) ~[?:?]
        at org.geysermc.geyser.platform.spigot.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:504) ~[?:?]
        at org.geysermc.geyser.platform.spigot.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:392) ~[?:?]
        at org.geysermc.geyser.platform.spigot.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[?:?]
        at org.geysermc.geyser.platform.spigot.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3542) ~[?:?]
        at org.geysermc.geyser.util.FileUtils.loadConfig(FileUtils.java:57) ~[?:?]
        at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onLoad(GeyserSpigotPlugin.java:144) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:435) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3766-Spigot-81b9def-a345bb9]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3766-Spigot-81b9def-a345bb9]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3766-Spigot-81b9def-a345bb9]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3766-Spigot-81b9def-a345bb9]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Please complete the following information:**
 - win10
 - spigot 1.20
 - 3.0-SNAPSHOT

**Comment by ElgarL** [comment]
Thanks, fixed in 3.0 release.
